_BASE_: "../COCO-Keypoints/keypoint_rcnn_R_50_FPN_3x.yaml"
MODEL:
  WEIGHTS: "models/detectron2-R50-KeypointDetection.pkl"
  META_ARCHITECTURE: "GeneralizedCamRCNN"
  ROI_HEADS:
    NAME: "HeightStandardROIHeads"
  ROI_BOX_HEAD:
    BBOX_REG_LOSS_WEIGHT: 10.0
  ROI_KEYPOINT_HEAD:
    NAME: "KRCNNConvDeconvUpsampleHead"
    LOSS_WEIGHT: 10.0
  KEYPOINT_ON: False
  HEIGHT_ON: False
  POINT_NET_ON: False
  HEIGHT_REFINE_ON: False
  HEIGHT_HEAD:
    LOSS_WEIGHT: 0.05
    SMOOTH_L1_BETA: 0.1
  POINT_NET:
    POOLING: "max"
    TEMPERATURE: 1.0
    BN: True
    TRANSFORM: True
    DETACH: False
    REFINE_TEMPERATURE: 1.0
    REFINE_LAYERS: 2  # Only applies at HEIGHT_REFINE_ON: TRUE
DATASETS:
  TRAIN: ("COCOScale2017Calib_train", )
  TEST: ()
SOLVER:
  # The dataset total size is 187206, 2000 for validation.
  IMS_PER_BATCH: 9  # 9 for 3 gpus 3 for 1
  RATIO_PANO360: (3, 1)  # 3 COCO, 1 CALIB
  BASE_LR: 0.01054 # 0.01054 for 3 gpus 0.003515 for 1 (diverges?)
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  AMP:
    ENABLED: True
  CLIP_GRADIENTS:
    CLIP_TYPE: norm
    CLIP_VALUE: 1.0
    ENABLED: true
    NORM_TYPE: 2.0
TEST:
  EVAL_PERIOD: 0
DATALOADER:
  NUM_WORKERS: 2
  FILTER_EMPTY_ANNOTATIONS: False
  ASPECT_RATIO_GROUPING: True
VIS_PERIOD: 500
FLOAT32_PRECISION: "medium"
SEED: 140421
